POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Evento de Inverno",
  "details": "Evento de teste",
  "maximumAttendees": 10
}

###
POST http://localhost:3333/events/48540bfe-3a3f-4eb0-8f23-9f0361a323db/attendees
Content-Type: application/json

{
  "name": "Nikolas",
  "email": "Nikolas@rocketseat.com"
}

###
GET http://localhost:3333/events/48540bfe-3a3f-4eb0-8f23-9f0361a323db

###
GET http://localhost:3333/attendees/10/badge

###
GET http://localhost:3333/attendees/8/check-in

###
GET http://localhost:3333/events/48540bfe-3a3f-4eb0-8f23-9f0361a323db/attendees

